### ISSUE TITLE
Añadir nombre producto en la Interfaz Caja.

### ISSUE THREAD

**Issue by cykrr** [cykrr/ProyectoDistribuida#2]
![image](https://github.com/cykrr/ProyectoDistribuida/assets/21285912/22a595ba-0293-483f-aaa1-84aaa0209e54)
Al obtener la información de un producto, quizás sería útil mostrar el nombre también para un poco de contexto.

**Comment by cykrr** [comment]
Se implementará un método `Servidor::obtenerItem(int idProducto)` el cual retornará directamente el producto. Además se añadirá un overload del método `Item::toString`. De esta forma podrán imprimir el objeto directamente con `System::out::println`.

**Comment by athersoft** [comment]
Implementado
