### ISSUE TITLE
Confusión respecto a atributo Cantidad de Item.

### ISSUE THREAD

**Issue by cykrr** [cykrr/ProyectoDistribuida#5]
![image](https://github.com/cykrr/ProyectoDistribuida/assets/21285912/5c195c6d-e1d1-40f5-980b-938afb34c21a)

Recordar que la API como tal (quien entrega la información de los productos) no trabaja con el concepto de "Stock" ya que esta es común para todos los supermercados. Dicha información deberá ser almacenada en la base de datos, sin embargo esta sólo se utilizará para la logística del local. Vale decir, registrar las ventas realizadas respecto al stock disponible (lo cual se implementará en el servidor, por lo cual no deberían preocuparse de ello).

Para aclarar la confusión se renombró el getter y la variable a `Servidor::getCantidadPack`.

**Comment by athersoft** [comment]
Originalmente la case item eran los items del carrito, por lo que cantidad era el numero de objetos en el carrito, pero ya se cambió la implementación usando la clase itemCarrito para ese manejo
